#!/usr/bin/env python3
"""Generate database/cleanup_organizations_sync_with_instances.sql.

Syncs admin-console organizations with the canonical instance registry:
  - all-ids.csv          : canonical instance ids + status (active allowlist)
  - all-organizations.csv: current admin-console organizations export

Output is a transactional SQL script that:
  1. Renames known code mismatches (sid-en -> siden-cfo, sid-en-kwn -> siden-kwn)
  2. Inserts active instances missing from admin
  3. Deletes admin organizations whose code is not in the active allowlist

Re-run: python3 dataprep/generate_organization_cleanup_sql.py
"""

import csv
from datetime import datetime, timezone
from pathlib import Path

DATAPREP_DIR = Path(__file__).resolve().parent
ALL_IDS_CSV = DATAPREP_DIR / "all-ids.csv"
ALL_ORGS_CSV = DATAPREP_DIR / "all-organizations.csv"
OUTPUT_PATH = DATAPREP_DIR.parent / "database" / "cleanup_organizations_sync_with_instances.sql"

# Explicit code renames applied before insert/delete (lowercased current code -> new code).
CODE_RENAMES = {
    "sid-en": "siden-cfo",
    "sid-en-kwn": "siden-kwn",
}

# Map all-ids.csv account_type values to organizations.account_type allowed values.
ACCOUNT_TYPE_MAP = {
    "employee": "employee",
    "demo": "demo",
    "client": "general customers",
    "siden": "employee",
    "project": "project",
}


def sql_str(value: str) -> str:
    """Quote a non-null string literal, escaping single quotes."""
    return "'" + value.replace("'", "''") + "'"


def load_active_allowlist():
    """Return dict of active instance id (lowercased) -> account_type from all-ids.csv."""
    allow = {}
    with open(ALL_IDS_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["status"].strip().lower() != "active":
                continue
            allow[row["id"].strip().lower()] = row["account_type"].strip().lower()
    return allow


def load_admin_orgs():
    """Return list of admin-console orgs (non-empty code) with normalized fields."""
    orgs = []
    with open(ALL_ORGS_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            code = (row.get("code") or "").strip()
            if not code:
                continue  # empty-code rows are skipped (manual follow-up)
            orgs.append(
                {
                    "uuid": row["id"].strip(),
                    "name": row["name"].strip(),
                    "code": code,
                    "code_lower": code.lower(),
                }
            )
    return orgs


def map_account_type(raw: str) -> str:
    if raw not in ACCOUNT_TYPE_MAP:
        raise ValueError(f"Unmapped account_type from all-ids.csv: {raw!r}")
    return ACCOUNT_TYPE_MAP[raw]


def build_sql():
    allow = load_active_allowlist()
    orgs = load_admin_orgs()

    # Effective code after applying renames, used for allowlist comparison.
    for o in orgs:
        o["effective_code"] = CODE_RENAMES.get(o["code_lower"], o["code_lower"])

    renames = [o for o in orgs if o["code_lower"] in CODE_RENAMES]
    to_delete = sorted(
        (o for o in orgs if o["effective_code"] not in allow),
        key=lambda x: x["code_lower"],
    )

    admin_effective_codes = {o["effective_code"] for o in orgs}
    missing_ids = sorted(cid for cid in allow if cid not in admin_effective_codes)

    lines = []
    lines.append("-- =============================================================================")
    lines.append("-- cleanup_organizations_sync_with_instances.sql")
    lines.append(f"-- Generated by dataprep/generate_organization_cleanup_sql.py on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append("-- Source: dataprep/all-ids.csv (active allowlist) + dataprep/all-organizations.csv")
    lines.append("-- Purpose:")
    lines.append("--   Sync admin-console organizations with the canonical active instance registry.")
    lines.append(f"--   Renames: {len(renames)}  Inserts: {len(missing_ids)}  Deletes: {len(to_delete)}")
    lines.append("--")
    lines.append("-- SAFETY:")
    lines.append("--   - Review the DELETE list below before running; it includes closed customer")
    lines.append("--     orgs (demo, kkn, thaisummit, etc.) that are absent from the active allowlist.")
    lines.append("--   - Deletes cascade to user_organizations, organization_invitations, support_* rows.")
    lines.append("--   - organization_trial_requests.organization_id is set to NULL (ON DELETE SET NULL).")
    lines.append("--   - Empty-code rows (e.g. 'SRT Demo') are intentionally skipped; fix manually.")
    lines.append("--   - Run in staging first with the preflight SELECT (Step 3) uncommented.")
    lines.append("-- =============================================================================")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    # Step 1: renames
    lines.append("-- -----------------------------------------------------------------------------")
    lines.append("-- Step 1: Rename mismatched codes to match the active instance registry")
    lines.append("-- -----------------------------------------------------------------------------")
    if not renames:
        lines.append("-- (none)")
        lines.append("")
    else:
        for o in renames:
            new_code = CODE_RENAMES[o["code_lower"]]
            acct = map_account_type(allow[new_code]) if new_code in allow else "employee"
            lines.append(
                f"UPDATE organizations SET code = {sql_str(new_code)}, name = {sql_str(new_code)}, "
                f"app_url = {sql_str(f'https://{new_code}.ideacarb.com')}, account_type = {sql_str(acct)}, updated_at = NOW()"
            )
            lines.append(f"WHERE lower(code) = {sql_str(o['code_lower'])};")
            lines.append("")

    # Step 2: inserts
    lines.append("-- -----------------------------------------------------------------------------")
    lines.append(f"-- Step 2: Insert {len(missing_ids)} active instances missing from admin console")
    lines.append("-- -----------------------------------------------------------------------------")
    if not missing_ids:
        lines.append("-- (none)")
        lines.append("")
    else:
        lines.append("WITH admin_user AS (")
        lines.append("  SELECT id")
        lines.append("  FROM users")
        lines.append("  WHERE email = 'admin@cfo.com'")
        lines.append("  LIMIT 1")
        lines.append("),")
        lines.append("missing_orgs AS (")
        lines.append("  SELECT *")
        lines.append("  FROM (")
        lines.append("    VALUES")
        value_rows = []
        for cid in missing_ids:
            acct = map_account_type(allow[cid])
            value_rows.append(
                f"      ({sql_str(cid)}, {sql_str(cid)}, {sql_str(f'https://{cid}.ideacarb.com')}, {sql_str(acct)})"
            )
        lines.append(",\n".join(value_rows))
        lines.append("  ) AS t(name, code, app_url, account_type)")
        lines.append(")")
        lines.append("INSERT INTO organizations (")
        lines.append("  name,")
        lines.append("  code,")
        lines.append("  app_url,")
        lines.append("  account_type,")
        lines.append("  is_initialized,")
        lines.append("  created_by")
        lines.append(")")
        lines.append("SELECT")
        lines.append("  mo.name,")
        lines.append("  mo.code,")
        lines.append("  mo.app_url,")
        lines.append("  mo.account_type,")
        lines.append("  FALSE,")
        lines.append("  (SELECT id FROM admin_user)")
        lines.append("FROM missing_orgs mo")
        lines.append("ON CONFLICT (code) DO UPDATE")
        lines.append("SET")
        lines.append("  name = EXCLUDED.name,")
        lines.append("  app_url = EXCLUDED.app_url,")
        lines.append("  account_type = EXCLUDED.account_type,")
        lines.append("  updated_at = NOW();")
        lines.append("")

    # Step 3: deletes
    lines.append("-- -----------------------------------------------------------------------------")
    lines.append(f"-- Step 3: Delete {len(to_delete)} organizations not in the active allowlist")
    lines.append("-- -----------------------------------------------------------------------------")
    lines.append("-- Related tables (FK to organizations):")
    lines.append("--   ON DELETE CASCADE: user_organizations, organization_invitations,")
    lines.append("--     support_conversations, support_messages, support_message_attachments")
    lines.append("--   ON DELETE SET NULL: organization_trial_requests.organization_id")
    lines.append("--   (support_messages / support_message_attachments also cascade via conversation)")
    lines.append("--")
    lines.append("-- Preflight (run before committing to review what will be removed):")
    lines.append("-- WITH obsolete AS (")
    lines.append("--   SELECT id, code, name FROM organizations")
    lines.append("--   WHERE code IS NOT NULL AND code <> ''")
    lines.append("--     AND lower(code) NOT IN (")
    lines.append("--       " + ", ".join(sql_str(cid) for cid in sorted(allow)))
    lines.append("--     )")
    lines.append("-- )")
    lines.append("-- SELECT 'organizations' AS table_name, count(*)::bigint AS n FROM obsolete")
    lines.append("-- UNION ALL SELECT 'user_organizations', count(*) FROM user_organizations uo JOIN obsolete o ON o.id = uo.organization_id")
    lines.append("-- UNION ALL SELECT 'organization_invitations', count(*) FROM organization_invitations oi JOIN obsolete o ON o.id = oi.organization_id")
    lines.append("-- UNION ALL SELECT 'support_conversations', count(*) FROM support_conversations sc JOIN obsolete o ON o.id = sc.organization_id")
    lines.append("-- UNION ALL SELECT 'support_messages', count(*) FROM support_messages sm JOIN obsolete o ON o.id = sm.organization_id")
    lines.append("-- UNION ALL SELECT 'support_message_attachments', count(*) FROM support_message_attachments sa JOIN obsolete o ON o.id = sa.organization_id")
    lines.append("-- UNION ALL SELECT 'organization_trial_requests (will SET NULL)', count(*) FROM organization_trial_requests tr JOIN obsolete o ON o.id = tr.organization_id;")
    lines.append("--")
    lines.append("-- Codes targeted for deletion:")
    for o in to_delete:
        lines.append(f"--   {o['code']}  ({o['name']})  uuid={o['uuid']}")
    if not to_delete:
        lines.append("--   (none)")
        lines.append("")
    else:
        lines.append("DELETE FROM organizations")
        lines.append("WHERE code IS NOT NULL AND code <> ''")
        lines.append("  AND lower(code) NOT IN (")
        lines.append("  " + ",\n  ".join(sql_str(cid) for cid in sorted(allow)))
        lines.append(");")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    # Verification
    lines.append("-- =============================================================================")
    lines.append("-- Verification snippets (run after COMMIT)")
    lines.append("-- =============================================================================")
    lines.append("")
    lines.append("-- 1) Admin codes still not in the active allowlist (expect only empty-code rows)")
    lines.append("-- SELECT code, name FROM organizations")
    lines.append("-- WHERE code IS NOT NULL")
    lines.append("--   AND lower(code) NOT IN (")
    lines.append("--   " + ", ".join(sql_str(cid) for cid in sorted(allow)))
    lines.append("--   );")
    lines.append("")
    lines.append("-- 2) Active allowlist ids still missing from admin (expect 0)")
    lines.append("-- SELECT a.id FROM (VALUES")
    lines.append("--   " + ", ".join(f"({sql_str(cid)})" for cid in sorted(allow)))
    lines.append("-- ) AS a(id)")
    lines.append("-- LEFT JOIN organizations o ON lower(o.code) = a.id")
    lines.append("-- WHERE o.id IS NULL;")
    lines.append("")

    return "\n".join(lines), renames, missing_ids, to_delete


def main():
    sql, renames, missing_ids, to_delete = build_sql()
    OUTPUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print(f"  Renames: {len(renames)} -> {[CODE_RENAMES[o['code_lower']] for o in renames]}")
    print(f"  Inserts: {len(missing_ids)} -> {missing_ids}")
    print(f"  Deletes: {len(to_delete)}")


if __name__ == "__main__":
    main()
